### PR TITLE
typo: changing 'federeate' for 'federate'

### PR DESCRIPTION
**Pull request by deccico**
**What this PR does / why we need it**: It fixes a typo in the documentation. Specifically a command.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by deccico** [comment]
I signed it

**Comment by irfanurrehman** [comment]
@deccico thanks for the fix.
Please fix the cla signing and i will merge this.

**Comment by hectorj2f** [comment]
@deccico it seems the problem is still happening

**Comment by deccico** [comment]
@hectorj2f the CLA signature is done.

**Comment by xunpan** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
