### PR TITLE
Fix service status not working issue

### LINKED ISSUE #1247: statusCollection not working for FederatedTypeConfig
**What happened**:
When enabling the status collection for a FederatedTypeConfig, the informer will be hanging there and keep writing following logs:
```
E0713 08:33:27.175542       1 reflector.go:374] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: expected gvk /v1, Kind=Service, but watch event object had gvk types.kubefed.io/v1beta1, Kind=FederatedService
E0713 08:33:27.178508       1 reflector.go:374] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: expected gvk /v1, Kind=Service, but watch event object had gvk types.kubefed.io/v1beta1, Kind=FederatedService
E0713 08:33:27.954000       1 reflector.go:374] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: expected gvk /v1, Kind=Service, but watch event object had gvk types.kubefed.io/v1beta1, Kind=FederatedService
```
**What you expected to happen**:
The informer should be running normally.

**How to reproduce it (as minimally and precisely as possible)**:
- S1: first create two clusters as per [user guide by kind](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/environments/kind.md) and then deploy Kubefed by Helm.

- S2: enable the status collection
```
[root@ecs-d8b6 kubefed]# kubectl patch federatedtypeconfigs.core.kubefed.io services --type='merge' --patch '{"spec":{"statusCollection":"Enabled","statusType":{"group":"core.kubefed.io","kind":"FederatedServiceStatus","pluralName":"federatedservicestatuses","version":"v1alpha1","scope":"Namespaced"}}}' -n kube-federation-system
```
<details>
<summary>After the patch, the `services` FederatedTypeConfig looks like follows:</summary>

```
[root@ecs-d8b6 kubefed]# kubectl get federatedtypeconfigs.core.kubefed.io services -n kube-federation-system -o yaml
apiVersion: core.kubefed.io/v1beta1
kind: FederatedTypeConfig
metadata:
  creationTimestamp: "2020-07-13T08:28:52Z"
  finalizers:
  - core.kubefed.io/federated-type-config
  generation: 2
  name: services
  namespace: kube-federation-system
  resourceVersion: "2273"
  selfLink: /apis/core.kubefed.io/v1beta1/namespaces/kube-federation-system/federatedtypeconfigs/services
  uid: 5a7f951c-406b-499f-8655-f2f208d57217
spec:
  federatedType:
    group: types.kubefed.io
    kind: FederatedService
    pluralName: federatedservices
    scope: Namespaced
    version: v1beta1
  propagation: Enabled
  statusCollection: Enabled
  statusType:
    group: core.kubefed.io
    kind: FederatedServiceStatus
    pluralName: federatedservicestatuses
    scope: Namespaced
    version: v1alpha1
  targetType:
    kind: Service
    pluralName: services
    scope: Namespaced
    version: v1
status:
  observedGeneration: 2
  propagationController: Running
  statusController: Running
```
</details>

And we can see the `.status. statusController` has been changed to `Running`.

- S3:  create a federated service

<details>
<summary>the yaml as follows:</summary>

```
[root@ecs-d8b6 kubefed]# cat example/sample1/federatedservice.yaml 
apiVersion: types.kubefed.io/v1beta1
kind: FederatedService
metadata:
  name: test-service
  namespace: test-namespace
spec:
  template:
    spec:
      selector:
        app: nginx
      type: NodePort
      ports:
        - name: http
          port: 80
  placement:
    clusters:
    - name: cluster2
    - name: cluster1
```
</details>

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)
- KubeFed version: v0.3.0
- Scope of installation (namespaced or cluster)
- Others

/kind bug
/assign

### PR DESCRIPTION
**Pull request by RainbowMango**
**What this PR does / why we need it**:
Fixed #1247
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1247

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by jimmidyson** [comment]
@RainbowMango thank you for this. I'm assuming we're missing test coverage here otherwise this would have been picked up before - would you be able to add some tests for this please?

**Comment by RainbowMango** [comment]
> would you be able to add some tests for this please?

@jimmidyson  thanks for your quick response :). I guess you mean the `tests` are E2E tests. Sure, I'd love to. 

I was wondering if we can take this PR focus on bug fix and move faster? Actually, not only the tests but the related docs should also be added too, for this I [opened an issue](https://github.com/kubernetes-sigs/kubefed/issues/1249) to follow these kinds of tasks.

**Comment by jimmidyson** [comment]
@RainbowMango I'm happy with that - thanks!

**Comment by hectorj2f** [comment]
I believe we should do a release this week to get this and other fixes

**Comment by RainbowMango** [comment]
Thank you for your understanding, @jimmidyson . I really like iterating.

> I believe we should do a release this week to get this and other fixes

Sounds great. the new release is `0.5.0` or `0.4.1` ?

**Pull request merged**
