### PR TITLE
Update runtime-controller v0.21.2 to v0.22.2 

### PR DESCRIPTION
**Pull request by tehlers320**
**What this PR does / why we need it**:
To fix https://github.com/kubernetes-sigs/kubefed/issues/1488

**Which issue(s) this PR fixes**:
Fixes #
https://github.com/kubernetes-sigs/kubefed/issues/1488
NOTE: per cluster, per resource rest metrics are now gone (a decision by upstream module maintainers)

So for example these metrics: 
```
rest_client_request_latency_seconds_bucket{url="https://10.11.11.11:5009/apis/coordination.k8s.io/v1?timeout=32s",verb="GET",le="0.512"} 12
rest_client_request_latency_seconds_bucket{url="https://10.11.11.115009/apis/coordination.k8s.io/v1?timeout=32s",verb="GET",le="+Inf"} 12
```

**Special notes for your reviewer**:
This is NOT tested WIP

### CODE REVIEW

**Comment by irfanurrehman** [comment]
@tehlers320 try signing/authorising the CLA again from the link in [this comment](https://github.com/kubernetes-sigs/kubefed/pull/1492#issuecomment-1041800495), please. If that does not resolve the issue in this PR and you sure you have signed/authorised the same, try opening a new PR. Signed CLA might be a prerequesite, rather then it being in flight for  the check to pass in the PR.

**Comment by tehlers320** [comment]
I finally got around to testing this

```
The extensions/v1beta1 and networking.k8s.io/v1beta1 API versions of Ingress is no longer served as of v1.22.
```

```
I0507 21:15:43.883207       1 controller.go:236] Target clusters' informers not synced
W0507 21:15:44.971781       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.2/tools/cache/reflector.go:167: failed to list extensions/v1beta1, Kind=Ingress: the server could not find the requested resource
E0507 21:15:44.971800       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.2/tools/cache/reflector.go:167: Failed to watch extensions/v1beta1, Kind=Ingress: failed to list extensions/v1beta1, Kind=Ingress: the server could not find the requested resource
W0507 21:15:47.501658       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.2/tools/cache/reflector.go:167: failed to list extensions/v1beta1, Kind=Ingress: the server could not find the requested resource
E0507 21:15:47.501715       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.2/tools/cache/reflector.go:167: Failed to watch extensions/v1beta1, Kind=Ingress: failed to list extensions/v1beta1, Kind=Ingress: the server could not find the requested resource
```

Should kubefed be released with versioning in partity with cluster version, much like autoscaler which whould always match your cluster version?

**Comment by tehlers320** [comment]
controller 0.9.0 with 10 clusters and 3000 federated resources
Screen Shot 2022-05-09 at 10 12 24 AM


this PR with 10 clusters and 3000 federated resources
Screen Shot 2022-05-09 at 10 11 44 AM

**Comment by irfanurrehman** [comment]
Thanks @tehlers320 for resurrecting this and posting the test results.
/lgtm

**Review by hectorj2f — COMMENTED** [review]
/lgtm

**Pull request merged**
