### PR TITLE
[WIP] Helm 3 Support

### PR DESCRIPTION
**Pull request by abrenneke**
**What this PR does / why we need it**:

The current Helm chart doesn't work on Helm 3. This moves the custom resources definitions to the new `crd` folders for the Helm 3 breaking changes.

**Special notes for your reviewer**:

I'm not sure how to make this backwards-compatible with Helm 2 - if anyone knows how to query the Helm version from within a chart, we can make this backwards compatible too (Leave in original `crds.yaml` files and only run them on Helm 2).

### CODE REVIEW

**Comment by pmorie** [comment]
@abrenneke thanks for the PR, but you need to sign the CLA. If you sign the CLA I will help you get this landed.

**Comment by abrenneke** [comment]
thanks @pmorie, I did sign it when I made this PR but there's some email mismatch I haven't had time to figure out yet

**Comment by gregov** [comment]
Hi @abrenneke, thank you for the inspiration, I have pushed your solution a bit further by maintaining the compatibility with Helm2. please see https://github.com/kubernetes-sigs/kubefed/pull/1189

**Comment by abrenneke** [comment]
Thanks @gregov!

**Pull request closed without merging**
