### PR TITLE
docs: adding documentation to add an array element using overrides

### LINKED ISSUE #1224: overrides `op: add` seems not to work as expected for array values
**What happened**:

Let say I have:
```
spec:
  template:
    spec:
      template:
        spec:
          initContainers:
            - name: myinitcontainer
              args:
                - --logtostderr
```

Adding an override on an array key using `op: add`:

```
spec:
  overrides:
    - clusterName: mycluster
      clusterOverrides:
        - path: "/spec/template/spec/initContainers/0/args"
          op: add
          value:
            - --init
  template:
    spec:
      template:
        spec:
          initContainers:
            - name: myinitcontainer
              args:
                - --logtostderr
```

Created this object in `mycluster`:
```
spec:
    initContainers:
      - name: myinitcontainer
         args:
          - --init
```

**What you expected to happen**:

Merging the two arguments in the array, thus creating this object in `mycluster` instead:
```
spec:
    initContainers:
      - name: myinitcontainer
         args:
          - --init
          - --logtostderr
```

**How to reproduce it (as minimally and precisely as possible)**:

Apply the earlier described manifests.

**Anything else we need to know?**:

I don't think so, if anything missing, please comment :).

**Environment**:
- KubeFed version: `v0.3.0`

/kind bug

### PR DESCRIPTION
**Pull request by ArchangelX360**
**What this PR does / why we need it**:

Adding a value to an array could be confusing for users, an example in the docs could alleviate the confusion.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1224

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by xunpan** [comment]
@ArchangelX360 
It is better to have a valid option for the case to me. `bar` seems not valid for `nginx`.

**Comment by ArchangelX360** [comment]
@xunpan agreed good catch, [`-q`](http://nginx.org/en/docs/switches.html) should be.

**Pull request merged**
