### PR TITLE
Add a shortname to replicaschedulingpreference

### PR DESCRIPTION
**Pull request by Abirdcfly**
**What this PR does / why we need it**:

Adds a short name `rsp` to `replicaschedulingpreference` which is easier to type in command line.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Abirdcfly** [comment]
I signed it

**Review by hectorj2f — COMMENTED** [review]
/approve

**Pull request merged**
