### PR TITLE
Remove FederatedIngress feature

### PR DESCRIPTION
**Pull request by hectorj2f**
**What this PR does / why we need it**:

This PR removes one of the alpha features FederatedIngress. This feature should not be part of kubefed core as mentioned in #1284. The main intention is to remove from kubefed those features that are not part of its core functionalities, and consequently mark kubefed as beta.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

#1284 
**Special notes for your reviewer**:

### CODE REVIEW

**Comment by irfanurrehman** [comment]
Thanks @hectorj2f.
The TOC in userguide still has reference to ingress dns. You might need to update the TOC.
Rest LGTM.

**Comment by hectorj2f** [comment]
@irfanurrehman Thanks for the review 😍 . I'll address that reference and move forward with the rest of pending tasks.

**Comment by irfanurrehman** [comment]
LGTM for me. Leaving it for another set of eyes to have a check. 
@makkes @jimmidyson

**Review by makkes — APPROVED** [review]

**Comment by makkes** [comment]
lgtm but my experience with this feature is limited so I'll leave the last call to @jimmidyson.

**Comment by jimmidyson** [comment]
/lgtm

Thanks @hectorj2f for this and for the reviews @irfanurrehman and @makkes!

**Pull request merged**
