### PR TITLE
fix: prefer core resources when enabling a type

### LINKED ISSUE #1078: kubedctl enable services has conflict with knative services
**What happened**:

run `$ ./bin/kubefedctl enable services --kubefed-namespace default`
returns `
F0802 15:16:29.293248   61760 enable.go:110] Error: Multiple resources are matched by "services": services, services.serving.knative.dev. A group-qualified plural name must be provided.`

The reason is that i installed knative services crd before. However, we cannot enable kube services using command line, since it has no group.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

install knative services and run kubefedctl enable services

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)
- KubeFed version
- Scope of installation (namespaced or cluster)
- Others

/kind bug

### PR DESCRIPTION
**Pull request by makkes**
**What this PR does / why we need it**:
When a resource type such as `pods` is `services` is passed to
`kubefedctl enable` and there's a match for this name in the `core`
group as well as another group, there was no way to tell `kubefedctl`
that the `core` resource should be enabled.

Now, whenever an API resource from the `core` group matches the
desired type to be enabled, this resource type is preferred.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1078 

**Special notes for your reviewer**:
Here's the steps to test this:

-  `kind create cluster`
- `kubectl apply --filename https://github.com/knative/serving/releases/download/v0.18.0/serving-crds.yaml`
- `make kubefedctl`
- `./bin/kubefedctl enable services --kubefed-namespace="default" -o yaml`

Before this change:
```
$ ./bin/kubefedctl enable services --kubefed-namespace="default" -o yaml
F1012 22:22:47.217201   66506 enable.go:111] Error: Multiple resources are matched by "services": services, services.serving.knative.dev. A group-qualified plural name must be provided.
```

With this change:
```
$ ./bin/kubefedctl enable services --kubefed-namespace="default" -o yaml
---
apiVersion: core.kubefed.io/v1beta1
kind: FederatedTypeConfig
[...]
```

### CODE REVIEW

**Comment by irfanurrehman** [comment]
@makkes thanks for doing this.
The implicitly selection of `core` when no group is specified and the core group is in the matches, seems fine to me.
However, it should be documented simply because its implicit. I think a good place to put it would be [here](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md#enabling-federation-of-an-api-type) in someway referring to details mentioned [here](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md#enabling-an-api-type-with-a-non-default-api-group).
Can you please do that.

**Comment by jimmidyson** [comment]
I wonder if we should do the same as kubectl does and follow API group/version priority when short names are used?

**Comment by makkes** [comment]
@jimmidyson do you have a hint where I would find out how kubectl does it?

**Comment by jimmidyson** [comment]
@makkes Check out `k8s.io/client-go/discovery` package, which allows you to list server resources.

**Comment by makkes** [comment]
> I wonder if we should do the same as kubectl does and follow API group/version priority when short names (or unqualified as in this case) are used?

We're already using `ServerPreferredResources` to fetch resources to consider so already following `kubectl`'s approach with regards to order. The only difference being that we error out when multiple resources match. In the service of keeping backwards-incompatible changes to a minimum, I would prefer to leave this PR as it is and follow-up with a PR that changes semantics to align with `kubectl`'s approach more. 

@jimmidyson wdyt?

**Comment by jimmidyson** [comment]
This PR effectively puts core v1 API as higher priority than anything else, which is reasonable and fixes the reported bug, so I'm happy to approve this PR as-is and follow up with a PR that aligns with kubectl semantics. I agree with @irfanurrehman  that this should be documented and then we can get this merged.

I think we can clean up the code quite a bit by using discovery client smarter, something like:

```go
restMapper := restmapper.NewDeferredDiscoveryRESTMapper(discoveryClient)
shortcutRestMapper := restmapper.NewShortcutExpander(restMapper, discoveryClient)

gvks, err := shortcutRestMapper.KindsFor(schema.GroupVersionResource{Group: optionalGroup, Version: optionalVersion, Resource: resource})
```

**Comment by makkes** [comment]
I agree and will add documentation soon!

**Comment by makkes** [comment]
@irfanurrehman @jimmidyson I added a section to the user guide.

**Pull request merged**
