### PR TITLE
Kind and Kubernetes upgrade

### PR DESCRIPTION
**Pull request by jimmidyson**
**What this PR does / why we need it**:

This PR upgrades to Kubernetes 1.21 for testing, and uses kind 0.11.1.

Some other changes include using `admissionregistration.k8s.io/v1`, available since Kubernetes
v1.16 (`v1beta1` will be removed in v1.22 so best to get this change in now imo).

Updated docs as necessary.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by makkes — APPROVED** [review]

**Comment by jimmidyson** [comment]
Sorry @makkes, rebased against master so lost lgtm...

**Pull request merged**
