### PR TITLE
kubefedcluster use cadata in kubeconfig file

### PR DESCRIPTION
**Pull request by huiwq1990**
**What this PR does / why we need it**:

Kubefedcluster's cadata build from member cluster's serviceaccount, it work well when kubefed directlly conntect to member cluster. In my case, kubefed connect to a proxyserver (it proxy all apiserver's traffic), and the proxyserver has a independent cabundle.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by RainbowMango** [comment]
It's an interesting use case.

@huiwq1990 I guess you joining cluster with a `kubeconfig` file which contains `proxyserver`'s CA.  The joining process is perfectly fine, but the following request to a member cluster will be disallowed as `proxyserver` failed to verify the certificate. Is that true?

**Comment by huiwq1990** [comment]
@RainbowMango Yes, kubefedcluster only use kubeconfig's apiserfver endpoint, it should use kubeconfig's cabundle too.

**Comment by irfanurrehman** [comment]
Looks legit to me. LGTM. @RainbowMango is this change allright with you?

**Review by makkes — CHANGES_REQUESTED** [review]
This needs to be documented somewhere. I would suggest [this page](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/cluster-registration.md) is the right place for it.

**Comment by huiwq1990** [comment]
@makkes @irfanurrehman I write a note specify the change.

**Comment by RainbowMango** [comment]
@irfanurrehman Yeah, I think the feature is reasonable. If there is CA data present in KUBECONFIG file, it is the preferred choice.
Thanks @huiwq1990 
/retest

**Comment by hectorj2f** [comment]
@makkes could you have a look again ? It looks good to me.

**Review by hectorj2f — APPROVED** [review]
/approve

**Pull request merged**
