### PR TITLE
Extend federated type config status API

### PR DESCRIPTION
**Pull request by RainbowMango**
**What this PR does / why we need it**:
This PR focus on take the API change onboard.

**Which issue(s) this PR fixes**:
Refer #1252

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by hectorj2f** [comment]
@RainbowMango is there any update here ? are you still working on this change ?

**Comment by RainbowMango** [comment]
Yes, but I'm busy with preparing [KubeCon](https://cncf.lfasiallc.cn/) recently.

As I mentioned before, the whole task is a little bit more complicated, so I suggested run it by iteration, so other guys could collaborate together.

**Comment by hectorj2f** [comment]
@RainbowMango In my opinion, I would suggest to add iterations that can be useful or self contained. If you add this new type without tests and without any connection to the rest of the code, it could end into an unused state if there is not more progress into this direction.

**Pull request closed without merging**
