### PR TITLE
controller/util: maintain a cache of cluster clients to reduce rest discovery

### PR DESCRIPTION
**Pull request by pjferrell**
Cluster client creation triggers rest discovery against the target cluster.  To reduce client creations, a cache has been added to federatedInformerImpl.  The cache is populated as cluster clients are used and kubefedcluster deletes clear the cached client corresponding to that cluster.

### CODE REVIEW

**Comment by xunpan** [comment]
@pjferrell 
I restarted the test and it failed again in `configmaps`. So, please help to check if it is related to your code change. Thanks.

**Comment by pjferrell** [comment]
@xunpan 
The federated configmap was being created with a cluster placement that selects all clusters.  This caused the "unlabeled" configmap to become adopted by sync controller.  When the federatedconfigmap was deleted (crud.go:213), sync controller removed the adopted configmap and the explicit delete of the configmap (crud.go:189) failed.

Test case would fail if the time between the two deletes was long enough for sync controller to complete the deletion.  With clusterClients cached, the time to propogate changes to clusters is shorter.

Original placement in test case:
`
  spec:
    placement:
      clusterSelector:
        matchLabels: {}
      clusters: []
`

New placement after test case change:
`
  spec:
    placement: {}
`

**Comment by xunpan** [comment]
@pjferrell 
Thanks for you update. I think it is fine. My question is:
is there any exception/condition to make a `generic.Client` invalid? We do not have client recreating mechanism in new code. Is that a case?

**Comment by pjferrell** [comment]
@xunpan Based on conversation with @marun, no controllers are currently handling secret changes for kudfedclusters.  This would be one case where generic.Client would need to be recreated.

Plan was to address this later when token rotation is handled.

**Comment by xunpan** [comment]
@pjferrell 
Thanks for your explanation.

/lgtm

**Comment by marun** [comment]
I'm reviewing this, I'd like to make sure I understand the test fix before merging.

**Comment by marun** [comment]
> @xunpan Based on conversation with @marun, no controllers are currently handling secret changes for kudfedclusters. This would be one case where generic.Client would need to be recreated.

I've filed #1132 to ensure followup on this behavior.

**Pull request merged**
