### PR TITLE
docker image slimming

### PR DESCRIPTION
**Pull request by wyyxd2017**
slimming the dockerfile!

### CODE REVIEW

**Comment by hectorj2f** [comment]
@wyyxd2017 Please, would you mind sharing the benefits of slimming the Dockerfile ? Is there any image size reduction ?

**Comment by wyyxd2017** [comment]
sorry,you are right.plz close this pr.Thanks!

**Comment by wyyxd2017** [comment]
> @wyyxd2017 Please, would you mind sharing the benefits of slimming the Dockerfile ? Is there any image size reduction ?

But,thiscan reduce the iamge's Layers.

**Comment by hectorj2f** [comment]
@wyyxd2017 I wanted to know how much we gain with this change.

**Comment by makkes** [comment]
I'm not sure I understand the benefit either and tried to replicate it myself:
```
REPOSITORY                                TAG                  IMAGE ID       CREATED              SIZE
quay.io/kubernetes-multicluster/kubefed   v0.6.1-3-gbdbb3305   a97764d5167e   About a minute ago   117MB
quay.io/kubernetes-multicluster/kubefed   v0.6.1-4-g07c9e286   84ef420dff36   4 minutes ago        117MB
```
One image is built from `master` branch, the other one with the commit from this very PR included. Both end up with the same size. The only benefit I can see right now is a reduction in the number of layers employed when building the final image.

I'm happy to merge the PR in any case but I'm led to believe that this will not change anything as for the final image size.

**Comment by makkes** [comment]
Plus, the repo that this PR came from doesn't exist, anymore. I'm not sure about the policy applied to our repo here but I'm not sure if that's a good sign mid-PR.

**Comment by hatowang** [comment]
> Plus, the repo that this PR came from doesn't exist, anymore. I'm not sure about the policy applied to our repo here but I'm not sure if that's a good sign mid-PR.
Yes,my original intention was to reduce  image size，but it was wrong.It's not  a good sign mid-PR.

**Comment by hatowang** [comment]
> Plus, the repo that this PR came from doesn't exist, anymore. I'm not sure about the policy applied to our repo here but I'm not sure if that's a good sign mid-PR.


Yes,my original intention was to reduce  image size，but it was wrong.It's not  a good sign mid-PR.

**Comment by wyyxd2017** [comment]
> Plus, the repo that this PR came from doesn't exist, anymore. I'm not sure about the policy applied to our repo here but I'm not sure if that's a good sign mid-PR.


Yes,my original intention was to reduce  image size，but it was wrong.It's not  a good sign mid-PR.

**Comment by makkes** [comment]
> > Plus, the repo that this PR came from doesn't exist, anymore. I'm not sure about the policy applied to our repo here but I'm not sure if that's a good sign mid-PR.
> 
> Yes,my original intention was to reduce image size，but it was wrong.It's not a good sign mid-PR.

How would you like to proceed here?

**Pull request closed without merging**
