### PR TITLE
Handle possible conflict in updating test labels on cluster

### PR DESCRIPTION
**Pull request by irfanurrehman**
**What this PR does / why we need it**:

The test on `master` after the last PR push seems to be failing because of a test flake. This PR fixes that

Ref: https://github.com/kubernetes-sigs/kubefed/runs/5593998914?check_suite_focus=true

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

Test fix

**Special notes for your reviewer**:

### CODE REVIEW

**Review by hectorj2f — APPROVED** [review]
/lgtm

**Comment by irfanurrehman** [comment]
@hectorj2f there was an update needed. Need LGTM label again. Thanks.

**Pull request merged**
