### PR TITLE
Add unit testing for pkg/schedulingtypes/updateOverridesMap

### PR DESCRIPTION
**Pull request by marun**
This PR is a follow-up to #1089 to ensure test coverage of the changed code and capture details about the fix in the changelog.

### CODE REVIEW

**Comment by xunpan** [comment]
LGTM

`updateOverridesMap` is a general function name but it handles only `replicas`. It seems not clear enough to understand logic from existing comments to me.

**Comment by marun** [comment]
@xunpan  If the function were exported and available for use outside the package you would have a point.  However, a name only has to be descriptive enough for its context, and I think this is sufficient for an unexported method.

**Comment by marun** [comment]
Rebased

**Comment by marun** [comment]
Rebased

**Pull request merged**
