### PR TITLE
Switch to go module and update dependencies

### LINKED ISSUE #778: Switch to go modules for dependancy management
switching to go modules for depndancy management

REF:

https://github.com/liggitt/gomodules/blob/master/README.md

https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/2019-03-19-go-modules.md

### PR DESCRIPTION
**Pull request by jimmidyson**
**What this PR does / why we need it**:
This PR switches to using go modules with latest go 1.13.

This PR also upgrades to Kubernetes 1.17.3 dependencies and controller-runtime 0.5.0.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #778

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by hectorj2f** [comment]
@jimmidyson Code changes looks good to me, but the test build failed https://travis-ci.org/kubernetes-sigs/kubefed/builds/645683679?utm_source=github_status&utm_medium=notification.

**Comment by jimmidyson** [comment]
Travis failed cloning from GitHub... Can you retrigger the build please?

**Comment by armandgrillet** [comment]
@font @irfanurrehman The assignee @shashidharatd does not seem to be active on GitHub since 3 months, you please retrigger the build? I am asking as you are named in https://github.com/kubernetes-sigs/kubefed/blob/master/OWNERS and reviewers of this PR.

**Comment by hectorj2f** [comment]
@armandgrillet the build has been already re-triggered. @jimmidyson can you confirm you reproduced a similar behavior locally when running the tests?

**Comment by jimmidyson** [comment]
Yes I will look at this this week. Sorry for the delay!

**Comment by jimmidyson** [comment]
Hmm not sure what's happening with the weird OWNERS thing - I've used git subtree for repo-infra as described in https://github.com/kubernetes/repo-infra#using-git-subtree but this is messing up OWNERS check. Looking how to fix that.

**Comment by jimmidyson** [comment]
This is ready for review again - if someone can please also trigger `/verify-owners` that label should be removed.

**Comment by pmorie** [comment]
I'm satisfied with CI to attest that things still work :)

/approve
/lgtm

**Comment by jimmidyson** [comment]
@pmorie Can you also please trigger verify owner with `/verify-owners` - I messed up OWNERS stuff when `subtree`ing `k/repo-infra`

**Comment by jimmidyson** [comment]
Sorry - bumped controller-runtime to latest release, 0.5.0. Tests are :heavy_check_mark:. Please can I get another `/lgtm` and `/verify-owners`?

**Comment by jimmidyson** [comment]
Gonna close and open new PR to see if that fixes the owners problem

**Pull request closed without merging**
