### PR TITLE
fixes #1454: add document for intersectWithClusterSelector

### LINKED ISSUE #1454: Documentation for setting intersectWithClusterSelector in RSP
**What would you like to be added**:
After the behaviour of `intersectWithClusterSelector` was introduced in #1393 the doc was not added for the same.

**Why is this needed**:
Let users know the usage of the feature.

/kind doc

### PR DESCRIPTION
**Pull request by xunpan**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
fixes #1454

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by irfanurrehman** [comment]
@xunpan can you please fix the commit message?

**Review by hectorj2f — COMMENTED** [review]
/lgtm

**Pull request merged**
