### PR TITLE
chore: Add labels to service

### PR DESCRIPTION
**Pull request by armandgrillet**
**What this PR does / why we need it**:
This PR adds the possibility to set labels for the controller manager's services. This is useful as new Prometheus versions [do not scrape services based on annotations anymore](https://github.com/helm/charts/tree/master/stable/prometheus-operator#prometheusioscrape).

**Special notes for your reviewer**:

### CODE REVIEW

**Review by hectorj2f — COMMENTED** [review]
Thanks @armandgrillet

**Review by hectorj2f — COMMENTED** [review]
/approve

**Review by makkes — APPROVED** [review]

**Review by hectorj2f — APPROVED** [review]

**Review by jimmidyson — CHANGES_REQUESTED** [review]
Please update chart readme then lgtm

**Review by jimmidyson — APPROVED** [review]

**Pull request merged**
