### PR TITLE
docs: add missing devel flag to helm commands (#1203)

### LINKED ISSUE #1203: Helm install documentation misses --devel flag
**What happened**:
When following the [guide](https://github.com/kubernetes-sigs/kubefed/blob/master/charts/kubefed/README.md) on installing the Helm chart, some commands do not work straight away, as the latest release of `kubefed` is a development release, and as such needs the `--devel` flag to be used.

**What you expected to happen**:
The given Helm commands work out of the box, specifically the `helm search` and `helm install`

**How to reproduce it (as minimally and precisely as possible)**:
```bash
❯  helm search kubefed
NAME                        	CHART VERSION	APP VERSION	DESCRIPTION
kubefed-charts/federation-v2	0.0.10       	           	Kubernetes Federation V2 helm chart
```

```bash
❯ helm install kubefed-charts/kubefed --name kubefed --namespace kube-federation-system
Error: failed to download "kubefed-charts/kubefed" (hint: running `helm repo update` may help)
```

**Anything else we need to know?**:
Adding the `--devel` made it work again.

```bash
❯ helm search kubefed --devel
NAME                        	CHART VERSION	APP VERSION	DESCRIPTION
kubefed-charts/kubefed      	0.2.0-alpha.1	           	KubeFed helm chart
kubefed-charts/federation-v2	0.0.10       	           	Kubernetes Federation V2 helm chart
```

```bash
❯ helm2 install kubefed-charts/kubefed --name kubefed --namespace kube-federation-system --devel
NAME:   kubefed
LAST DEPLOYED: Thu Mar 12 14:21:16 2020
NAMESPACE: kube-federation-system
STATUS: DEPLOYED

RESOURCES:
...
```

**Environment**:
- Kubernetes version (use `kubectl version`)
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
- KubeFed version
```
0.2.0-alpha.1
```

/kind bug

### PR DESCRIPTION
**Pull request by Addono**
**What this PR does / why we need it**:
Helm search and install needs the devel flag, as currently the latest version of the chart is still a development release. However, this is not included in the documentation. As such, following the documentation will not lead to the desired effect.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1203

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Addono** [comment]
I signed it

**Comment by Addono** [comment]
/check-sla \check-sla
I signed it

**Comment by jimmidyson** [comment]
@Addono There's still something wrong with your CLA - can you please check https://identity.linuxfoundation.org/projects/cncf to see if there's anything you still need to do?

**Comment by Addono** [comment]
@jimmidyson Fixed the CLA issue

**Pull request merged**
