### PR TITLE
chore: disable FederatedIngress feat by default

### PR DESCRIPTION
**Pull request by hectorj2f**
**What this PR does / why we need it**:
Disable by default the alpha feature FederatedIngress.
Tests would continue exercising this feature cause we explicitly enable it in the e2e tests.
relates to: https://github.com/kubernetes-sigs/kubefed/issues/1284
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by jimmidyson** [comment]
/approve

Will wait for lgtm from another maintainer.

**Comment by hectorj2f** [comment]
@jimmidyson It should not be affected cause we don't disable the feature for the tests, I'll take a look at it later.

**Comment by jimmidyson** [comment]
I think you'll need to enable the feature when deploying for e2e

**Comment by jimmidyson** [comment]
@yuswift @shashidharatd You commented on #1284 so I'm pinging you for visibility. This PR disables the feature by default and deprecates it for removal in a future version.

@irfanurrehman @RainbowMango Could you review please and lgtm if you're OK with this PR?

**Review by makkes — APPROVED** [review]

**Pull request merged**
