### PR TITLE
Upgrade kind dependency to v0.6.1 to acquire k8s 1.16+

### PR DESCRIPTION
**Pull request by yue9944882**

### CODE REVIEW

**Comment by hectorj2f** [comment]
@yue9944882 It seems the kubernetes cluster doesn't reach the readiness, and times out. I suggest you run it locally.

**Comment by yue9944882** [comment]
@hectorj2f thanks, sadly i didn't re'pro the failure locally.. let me figure out the gap..

**Comment by RainbowMango** [comment]
@yue9944882 
Why not bump kind to [v0.7.0](https://github.com/RainbowMango/kind/releases/tag/v0.7.0)?

**Comment by yue9944882** [comment]
closing in favor of #1221

**Pull request closed without merging**
