### PR TITLE
Remove unused cluster registry dep

### PR DESCRIPTION
**Pull request by marun**
As of #876 kubefed no longer depends on cluster registry.

### CODE REVIEW

**Comment by shashidharatd** [comment]
Nice Cleanup! Thanks for this.
LGTM.

**Comment by xunpan** [comment]
LGTM

I guess prune rule in `Gopkg.toml` should also be cleaned.

**Comment by marun** [comment]
> I guess prune rule in `Gopkg.toml` should also be cleaned.

Done!

**Pull request merged**
