### PR TITLE
external dns setup and required kubefed feature gate documentation

### PR DESCRIPTION
**Pull request by rwong2888**

### CODE REVIEW

**Comment by yuswift** [comment]
Maybe we don't need the docs anymore. The kubefed community is going to remove this feature. See this [pr](https://github.com/kubernetes-sigs/kubefed/pull/1351).

**Comment by yuswift** [comment]
Maybe we don't need the docs anymore. The kubefed community is going to remove this feature. See this [pr](https://github.com/kubernetes-sigs/kubefed/pull/1351).

**Comment by rwong2888** [comment]
Closing as per @yuswift 's comment that this feature is deprecating

**Pull request closed without merging**
