### PR TITLE
docs: update README.md to reflect current projectstate

### PR DESCRIPTION
**Pull request by svenbs**
**What this PR does / why we need it**:
The README.md says that the project is an alpha version, while since version v0.1.0 it is a beta version.

### CODE REVIEW

**Comment by svenbs** [comment]
I signed the CLA

**Comment by jimmidyson** [comment]
@svenbs Thanks for the PR - could you please sign the CLA?

**Comment by svenbs** [comment]
@jimmidyson : I signed the CLA

**Pull request merged**
