### PR TITLE
chore: remove deprecated chart from repo

### PR DESCRIPTION
**Pull request by makkes**
**What this PR does / why we need it**:
Removing the old federation-v2 from the Helm repo as this chart just leads to confusion on user's side and it's deprecated,
anyway.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
no issue

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by makkes** [comment]
@irfanurrehman fyi

**Comment by irfanurrehman** [comment]
@makkes thanks for doing this.
/lgtm

**Pull request merged**
