### PR TITLE
Add pod level annotations for the kubefed controller

### LINKED ISSUE #1447: Add custom annotations to pod level at deployment
**What would you like to be added**:
Would like to have annotations added at the pod level when the kubefed controller is deployed, currently its only available to set at the deployment level.

**Why is this needed**:
This is needed as we require some annotations to be scrapped or identified via other products in kube pods for other functionality to work in the cluster, e.g. [Datadog annotations](https://docs.datadoghq.com/agent/kubernetes/integrations/?tab=kubernetes#configuration) for scrapping the kubefed custom metrics. Currently annotations are only available to be set at the [deployment level](https://github.com/kubernetes-sigs/kubefed/blob/master/charts/kubefed/charts/controllermanager/templates/deployments.yaml#L9) and they are not propagated to the pod when deployed.
There is annotations at the pod level for the controller, but this is only for the [rollme feature](https://github.com/kubernetes-sigs/kubefed/blob/master/charts/kubefed/charts/controllermanager/templates/deployments.yaml#L23), and no other custom ones can be added.

/kind feature

### PR DESCRIPTION
**Pull request by nitinatgh**
Added in description to the README.md
Bumped up the chart version of the controller manager
Bumped up the dependency version

Added a new annotation and left the existing one incase it breaks any other previous changes. But not sure if the previous one created was done correctly, so have left it intact.

**What this PR does / why we need it**:  To have annotations set at the pod level for the kubefed controller. Currently it's only restricted to the deployment level.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1447

**Special notes for your reviewer**:  I have created a new annotation as the [previous one committed](https://github.com/kubernetes-sigs/kubefed/commit/2d92596d791f8ee3d727380c27e4e5bc958ae76e#diff-2489ff8f2c64dc0dc988a4d074b2b0f04d82c3d98934dcf0fcc3165e6bb97ed3R9) seems to be incorrect and I didn't want to have any breaking changes related to it.

I have tested the changes in a local kind cluster, below is the output from running the helm upgrades

Added the following in the values.yaml
```
...
  imagePullSecrets: []
  # - name: secretName

  controller:
    annotations: {}
    podAnnotations:
      ad.datadoghq.com/controller-manager.check_names: |
        ["openmetrics"]
      ad.datadoghq.com/controller-manager.init_configs: |
        [{}]
      ad.datadoghq.com/controller-manager.instances: |
        [
          {
            "prometheus_url": "http://%%host%%:%%port%%/metrics",
            "namespace": "kube-federation-system",
            "metrics": [ "*" ],
            "send_distribution_buckets": true,
            "send_distribution_counts_as_monotonic": true,
            "send_histograms_buckets": true,
            "send_monotonic_counter": true
          }
        ]
    replicaCount: 2
    repository: quay.io/kubernetes-multicluster
    image: kubefed
...
```
helm upgrade dry-run
```
helm --namespace kube-federation-system upgrade -i kubefed ./kubefed --create-namespace --dry-run

...
# Source: kubefed/charts/controllermanager/templates/deployments.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefed-controller-manager
  namespace: kube-federation-system
  labels:
    kubefed-control-plane: controller-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      kubefed-control-plane: controller-manager
  strategy: {}
  template:
    metadata:
      labels:
        kubefed-control-plane: controller-manager
      annotations:
        ad.datadoghq.com/controller-manager.check_names: |
          ["openmetrics"]
        ad.datadoghq.com/controller-manager.init_configs: |
          [{}]
        ad.datadoghq.com/controller-manager.instances: |
          [
            {
              "prometheus_url": "http://%%host%%:%%port%%/metrics",
              "namespace": "kube-federation-system",
              "metrics": [ "*" ],
              "send_distribution_buckets": true,
              "send_distribution_counts_as_monotonic": true,
              "send_histograms_buckets": true,
              "send_monotonic_counter": true
            }
          ]
    spec:
      nodeSelector:
        {}
      tolerations:
...
```

helm upgrade
```
$ kubectl get pods -A

NAMESPACE                NAME                                             READY   STATUS    RESTARTS   AGE
kube-federation-system   kubefed-admission-webhook-67fb48d5f7-hhjhm       1/1     Running   0          23h
kube-federation-system   kubefed-controller-manager-76c659dd6b-924tp      1/1     Running   0          11s
kube-federation-system   kubefed-controller-manager-76c659dd6b-rq27r      1/1     Running   0          13s
kube-system              coredns-558bd4d5db-g29mw                         1/1     Running   0          24h
kube-system              coredns-558bd4d5db-rfggp                         1/1     Running   0          24h
kube-system              etcd-cluster1-control-plane                      1/1     Running   0          24h

$ kubectl describe pod -n kube-federation-system  kubefed-controller-manager-76c659dd6b-924tp

Name:         kubefed-controller-manager-76c659dd6b-924tp
Namespace:    kube-federation-system
Priority:     0
Node:         cluster1-control-plane/172.18.0.2
Start Time:   Wed, 25 Aug 2021 13:55:07 +0100
Labels:       kubefed-control-plane=controller-manager
              pod-template-hash=76c659dd6b
Annotations:  ad.datadoghq.com/controller-manager.check_names: ["openmetrics"]
              ad.datadoghq.com/controller-manager.init_configs: [{}]
              ad.datadoghq.com/controller-manager.instances:
                [
                  {
                    "prometheus_url": "http://%%host%%:%%port%%/metrics",
                    "namespace": "kube-federation-system",
                    "metrics": [ "*" ],
                    "send_distribution_buckets": true,
                    "send_distribution_counts_as_monotonic": true,
                    "send_histograms_buckets": true,
                    "send_monotonic_counter": true
                  }
                ]
              kubectl.kubernetes.io/restartedAt: 2021-08-25T12:55:04Z
Status:       Running
IP:           10.244.0.64
IPs:
  IP:           10.244.0.64
...
```

Also would like to give a special thanks to https://github.com/kiich for helping me out on this change! 

Thanks 

Nitin

### CODE REVIEW

**Comment by nitinatgh** [comment]
I've set my primary e-mail to my work one, so hopefully this should be working for the CLA sign off.

**Comment by nitinatgh** [comment]
I signed it

**Comment by nitinatgh** [comment]
@yuswift , should I close this PR and open anew one and try again?

**Comment by yuswift** [comment]
> @yuswift , should I close this PR and open anew one and try again?

I guess so...

**Comment by nitinatgh** [comment]
Closing and retrying to try and have the CLA signed off automatically

**Pull request closed without merging**
