### PR TITLE
bump Ingress typeconfig version from v1beta1 to v1

### PR DESCRIPTION
**Pull request by swiftslee**
**What this PR does / why we need it**:
To support k8s v1.22
**Which issue(s) this PR fixes** *:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by jimmidyson — APPROVED** [review]

**Comment by yuswift** [comment]
> /lgtm
> /approve

Thanks for your review. The e2e test fails because the k8s version is not v1.22 I guess.

**Comment by hectorj2f** [comment]
@yuswift Please, could you help us and bump the kubebuilder version ?

**Pull request closed without merging**
