### PR TITLE
fix: if annotations is nil, override to add or replace mutil element …

### PR DESCRIPTION
**Pull request by CharlesQQ**
…will be failed

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by CharlesQQ** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)



> 感谢您的拉取请求。在我们查看您的拉取请求之前，您需要签署一份贡献者许可协议 (CLA)。
> 
> 📝 **请按照https://git.k8s.io/community/CLA.md#the-contributor-license-agreement上的说明签署 CLA。**
> 
> CLA 签名可能需要几分钟才能完全注册；之后，请在此处回复一条新评论，我们将进行验证。谢谢。
> 
> * 如果您已经签署了 CLA，则可能我们没有您的 GitHub 用户名，或者您使用的是其他电子邮件地址。检查您现有的 CLA 数据并验证您的[电子邮件是否设置在您的 git commits 上](https://help.github.com/articles/setting-your-email-in-git/)。
> * 如果您以公司身份签署 CLA，请使用您组织的凭据登录https://identity.linuxfoundation.org/projects/cncf以获得授权。
> * 如果您已完成上述操作，但仍遇到被报告为未签名的 CLA 问题，请在 Linux 基金会帮助台上登记一张票：[https](https://support.linuxfoundation.org/) : [//support.linuxfoundation.org/](https://support.linuxfoundation.org/)
> * 如果您在 Linux Foundation Helpdesk 中遇到任何问题，请向备用电子邮件支持地址发送消息：[login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)
> 
> [此处](https://git.k8s.io/community/contributors/guide/pull-requests.md)提供了有关使用 PR 评论与我互动的说明。如果您对我的行为有任何疑问或建议，请针对[kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:)存储库提出问题。我了解[此处](https://go.k8s.io/bot-commands)列出的命令。

**Comment by CharlesQQ** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

signed a CLA already

**Comment by yuswift** [comment]
> > Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> > 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> > It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> > 
> > * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> > * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> > * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> > * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)
> 
> signed a CLA already

please comment `I signed it`

**Comment by xunpan** [comment]
@CharlesQQ 
1. please sign CLA correctly.
2. I guess it should be related to `json-patch` that when there is no annotation item, it failed in applying the patch. However, fixed in `kubefed` can be considered as workaround. Is this what you want?

**Comment by jimmidyson** [comment]
Can we get a test for this added please?

**Comment by CharlesQQ** [comment]
I signed it  @yuswift , please check again

**Comment by CharlesQQ** [comment]
@xunpan yes, it annonations is nil, json-patch dose not  work

**Comment by CharlesQQ** [comment]
@jimmidyson  here is test 

1.  this test will panic  in `patch.Apply(original)`
```
	original := []byte(`{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"labels":{"name":"mo-dashboard-api-prod","online":"mo-dashboard-api-prod","release":"25"},"name":"mo-dashboard-api-prod","namespace":"default"},"spec":{"replicas":6,"revisionHistoryLimit":999,"selector":{"matchLabels":{"name":"mo-dashboard-api-prod","online":"mo-dashboard-api-prod"}},"strategy":{"rollingUpdate":{"maxSurge":"100%","maxUnavailable":0},"type":"RollingUpdate"},"template":{"dnsPolicy":"ClusterFirst","metadata":{"labels":{"name":"mo-dashboard-api-prod","online":"mo-dashboard-api-prod","release":25}},"nodeSelector":{"group":"momo"},"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"spec":{"containers":[{"env":[{"name":"BOOTSCRIPT","value":"/home/deploy/mo-dashboard-api/start.sh"},{"name":"CPU_COUNT","value":"2"},{"name":"DEPLOY_DIR","value":"/home/deploy"},{"name":"DOMAIN_NAME","value":"mo-dashboard-api.momo.com"},{"name":"LOGPATH","value":"/home/logs/mo-dashboard-api"},{"name":"PORT","value":"8000"},{"name":"PRO_MODULE","value":"mo-dashboard-api"},{"name":"UPSTREAM_NAME","value":"mo-dashboard-api_backend"},{"name":"WEIGHT","value":"100"}],"image":"docker.momo.com/prod/mo-dashboard-api:2f66f4f-20210521143939","imagePullPolicy":"Always","lifecycle":{"preStop":{"exec":{"command":["/bin/bash","/home/deploy/stop.sh"]}}},"name":"mo-dashboard-api-prod","resources":{"limits":{"cpu":"8.0","memory":"8Gi"},"requests":{"cpu":"4.0","memory":"8Gi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/etc/resolv.conf","name":"resolv","readOnly":true},{"mountPath":"/etc/localtime","name":"localtime","readOnly":true},{"mountPath":"/home/.history/","name":"kvconfig-volume"},{"mountPath":"/dev/shm","name":"tmpfs"},{"mountPath":"/home/log1/","name":"logs","readOnly":false},{"mountPath":"/etc/momo","name":"momoenv","readOnly":true}]}]},"terminationGracePeriodSeconds":30,"volumes":[{"hostPath":{"path":"/home/logs/docker/mo-dashboard-api-prod/mo-dashboard-api-prod-0.0.1/","type":""},"name":"logs"},{"hostPath":{"path":"/etc/momo/product/","type":""},"name":"momoenv"},{"hostPath":{"path":"/etc/localtime","type":""},"name":"localtime"},{"hostPath":{"path":"/etc/resolv.conf","type":""},"name":"resolv"},{"hostPath":{"path":"/home/.history/.docker-secaudit/","type":""},"name":"kvconfig-volume"},{"hostPath":{"path":"/dev/shm","type":""},"name":"tmpfs"}]}}}`)
	patchJSON := []byte(`[
		{"op": "replace", "path":"/metadata/annonations/octopus~1partition", "value": "90%"},
		{"op": "add", "path":"/metadata/annonations/octopus~1partition", "value": "70%"},
		{"op": "replace", "path":"/metadata/annonations/octopus~1paused", "value": "false"}
	 ]`)

	patch, err := jsonpatch.DecodePatch(patchJSON)
	if err != nil {
		panic(err)
	}

	modified, err := patch.Apply(original)
	if err != nil {
		panic(err)
	}
```

2. so I  add  annonations for original and test run sueeessfully
```
	original := []byte(`{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annonations": {"octopus/partition":"80%"}, "labels":{"name":"mo-dashboard-api-prod","online":"mo-dashboard-api-prod","release":"25"},"name":"mo-dashboard-api-prod","namespace":"default"},"spec":{"replicas":6,"revisionHistoryLimit":999,"selector":{"matchLabels":{"name":"mo-dashboard-api-prod","online":"mo-dashboard-api-prod"}},"strategy":{"rollingUpdate":{"maxSurge":"100%","maxUnavailable":0},"type":"RollingUpdate"},"template":{"dnsPolicy":"ClusterFirst","metadata":{"labels":{"name":"mo-dashboard-api-prod","online":"mo-dashboard-api-prod","release":25}},"nodeSelector":{"group":"momo"},"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"spec":{"containers":[{"env":[{"name":"BOOTSCRIPT","value":"/home/deploy/mo-dashboard-api/start.sh"},{"name":"CPU_COUNT","value":"2"},{"name":"DEPLOY_DIR","value":"/home/deploy"},{"name":"DOMAIN_NAME","value":"mo-dashboard-api.momo.com"},{"name":"LOGPATH","value":"/home/logs/mo-dashboard-api"},{"name":"PORT","value":"8000"},{"name":"PRO_MODULE","value":"mo-dashboard-api"},{"name":"UPSTREAM_NAME","value":"mo-dashboard-api_backend"},{"name":"WEIGHT","value":"100"}],"image":"docker.momo.com/prod/mo-dashboard-api:2f66f4f-20210521143939","imagePullPolicy":"Always","lifecycle":{"preStop":{"exec":{"command":["/bin/bash","/home/deploy/stop.sh"]}}},"name":"mo-dashboard-api-prod","resources":{"limits":{"cpu":"8.0","memory":"8Gi"},"requests":{"cpu":"4.0","memory":"8Gi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/etc/resolv.conf","name":"resolv","readOnly":true},{"mountPath":"/etc/localtime","name":"localtime","readOnly":true},{"mountPath":"/home/.history/","name":"kvconfig-volume"},{"mountPath":"/dev/shm","name":"tmpfs"},{"mountPath":"/home/log1/","name":"logs","readOnly":false},{"mountPath":"/etc/momo","name":"momoenv","readOnly":true}]}]},"terminationGracePeriodSeconds":30,"volumes":[{"hostPath":{"path":"/home/logs/docker/mo-dashboard-api-prod/mo-dashboard-api-prod-0.0.1/","type":""},"name":"logs"},{"hostPath":{"path":"/etc/momo/product/","type":""},"name":"momoenv"},{"hostPath":{"path":"/etc/localtime","type":""},"name":"localtime"},{"hostPath":{"path":"/etc/resolv.conf","type":""},"name":"resolv"},{"hostPath":{"path":"/home/.history/.docker-secaudit/","type":""},"name":"kvconfig-volume"},{"hostPath":{"path":"/dev/shm","type":""},"name":"tmpfs"}]}}}`)
	patchJSON := []byte(`[
		{"op": "replace", "path":"/metadata/annonations/octopus~1partition", "value": "90%"},
		{"op": "add", "path":"/metadata/annonations/octopus~1partition", "value": "70%"},
		{"op": "replace", "path":"/metadata/annonations/octopus~1paused", "value": "false"}
	 ]`)

	patch, err := jsonpatch.DecodePatch(patchJSON)
	if err != nil {
		panic(err)
	}
	modified, err := patch.Apply(original)
	if err != nil {
		panic(err)
	}
```

**Pull request closed without merging**
