### PR TITLE
feat:Use patch to replace update in generic client for multi cases

### LINKED ISSUE #1394: [UMBRELLA] Update to Patch
**What would you like to be added**:
Use `Patch` operations instead of `Update` across the whole codes.

**Why is this needed**:
- less conflicts
- less error logs
- less reconciliations

**TODO List**:
- #1389 
- more actions will be appended after walking all codes

/kind feature

### PR DESCRIPTION
**Pull request by qmhu**
**What this PR does / why we need it**:
As issue #1389 , replaced **Update** in remained codes

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1394 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by yuswift** [comment]
ci failed @qmhu

**Comment by yuswift** [comment]
@hectorj2f could you retest the ci? Thank you so much.

**Comment by qmhu** [comment]
@font @gyliu513 @mars1024 @hectorj2f  cloud you review this pr? tks

**Comment by mars1024** [comment]
ref to #1394

**Review by hectorj2f — COMMENTED** [review]
/lgtm

**Pull request merged**
