### PR TITLE
use merge-patch on finalizer operations to resolve racing conflicts

### PR DESCRIPTION
**Pull request by mars1024**
**What this PR does / why we need it**:
`Patch` is more efficient than `Update` to handle racing conditions on high-frequency changes of objects, which is also recommended by kubernetes spec.

**Which issue(s) this PR fixes**:
Try to avoid some errors, like [https://github.com/kubernetes-sigs/kubefed/blob/4dbd63b07de4b2bcebf3bd2632e0ec08e254f4c3/pkg/controller/sync/controller.go#L283](https://github.com/kubernetes-sigs/kubefed/blob/4dbd63b07de4b2bcebf3bd2632e0ec08e254f4c3/pkg/controller/sync/controller.go#L283)

### CODE REVIEW

**Comment by yuswift** [comment]
There are many `Update` operations. Could you tell me why do you only change the `finalizer` update operation?

**Comment by mars1024** [comment]
> There are many `Update` operations. Could you tell me why do you only change the `finalizer` update operation?

Actually, this is only the first step. I'll try to use more `Patch` after this merged.

**Comment by yuswift** [comment]
> > There are many `Update` operations. Could you tell me why do you only change the `finalizer` update operation?
> 
> Actually, this is only the first step. I'll try to use more `Patch` after this merged.

@hectorj2f What's your suggestion?

**Review by hectorj2f — COMMENTED** [review]
I'd like to see a more consistent and global change of Update to Patch operations across the whole code. I agree with @mars1024  here.

**Comment by mars1024** [comment]
> I'd like to see a more consistent and global change of Update to Patch operations across the whole code. I agree with @mars1024 here.

Thanks for your agreement, @hectorj2f , and I think this PR is already ready as the first step.

**Review by makkes — APPROVED** [review]

**Comment by mars1024** [comment]
friendly ping @hectorj2f for approval or more comments

**Review by hectorj2f — COMMENTED** [review]
@mars1024 What did it happen with the rest of changes to use Patch instead of Update ?

**Comment by mars1024** [comment]
> @mars1024 What did it happen with the rest of changes to use Patch instead of Update ?

Recently I didn't have much time on this, so I opened an help-wanted UMBRELLA issue to track the rest changes.

**Pull request merged**
