### PR TITLE
chore: use cert-mananager.io/v1 group/version

### PR DESCRIPTION
**Pull request by alejandroEsc**
**What this PR does / why we need it**:
Changes cert-manager resources to those whose group/version are "cert-manager.io/v1"

This was tested on a kind cluster with the latest version of cert-manager. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by alejandroEsc** [comment]
@jimmidyson here is what you were suggesting from PR: https://github.com/kubernetes-sigs/kubefed/pull/1288. This would be a breaking change. The alternative approach would be to change the defaults to those we manually set here. Let me know what you prefer.

**Review by hectorj2f — APPROVED** [review]

**Review by makkes — APPROVED** [review]

**Comment by irfanurrehman** [comment]
@alejandroEsc thanks for doing this.
/approve

**Pull request merged**
