### PR TITLE
docs[userguide]: clean up redundant text

### PR DESCRIPTION
**Pull request by samvantran**
**What this PR does / why we need it**:
Very minor cleanup of some repeated text

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:

### CODE REVIEW

**Review by hectorj2f — COMMENTED** [review]
/lgtm

**Comment by hectorj2f** [comment]
@samvantran you need to sign the contributing license agreement. Otherwise the build cla/Linux foundation will fail.

**Comment by samvantran** [comment]
Okay should be good to go now

**Pull request merged**
