### PR TITLE
Replica rebalance reconciliation fix

### PR DESCRIPTION
**Pull request by irfanurrehman**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
Fixes https://github.com/kubernetes-sigs/kubefed/issues/1369
**Special notes for your reviewer**:
~~I will probably update relevant unit tests also, in a short while.~~
Updated unit tests.

### CODE REVIEW

**Comment by irfanurrehman** [comment]
cc @marinoborges

**Comment by hectorj2f** [comment]
@irfanurrehman Have you manage to replica the same issue https://github.com/kubernetes-sigs/kubefed/issues/1369 ? From you last comment I understand you asked for those files.

**Review by hectorj2f — COMMENTED** [review]
@irfanurrehman Could we get an e2e that exercise this function a part from this unit test ?

**Review by hectorj2f — APPROVED** [review]

**Comment by irfanurrehman** [comment]
@hectorj2f Apologies, for not noticing this earlier. Was on PTO.

> @irfanurrehman Have you manage to replica the same issue #1369 ? From you last comment I understand you asked for those files.
Yes, I got the scenario and the yamls from @marinoborges offline.

> @irfanurrehman Could we get an e2e that exercise this function a part from this unit test ?
 Adding an e2e for this did not appear to be very straight forward. Would involve changing atleast one of the kind cluster runs with an additional node, managing labels (or taints) on that node wrt the scheduled pod, while also ensuring that this does not affect the other tests using the same cluster. I could not justify the additional value wrt to what the unit test already does.

Thanks for reviewing it anyways.

**Pull request merged**
