### PR TITLE
Update CI to test against kube v1.15.0

### LINKED ISSUE #1079: Missing spec field causes Controller CrashLoopBackOff
**What happened**:
FederatedSecrets / FederatedConfigmaps takes up to 30 minutes to be visible in
joined clusters. After several minutes some of them are visible,.....after minutes next
ConfigMaps comes (maybe)
You can't rely on the Secrects or ConfigMaps being synchronized at all. Some are not sync

**What you expected to happen**:
new created Federated#### comes within minutes and not hours

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

- KubeFed version
``` 
kubefedctl version: version.Info{Version:"v0.1.0-rc5-dirty", GitCommit:"99be0218bf5ac7d560ec0d7c2cfbfcbb86ba2d61", GitTreeState:"dirty", BuildDate:"2019-08-01T15:41:41Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}

``` 
- Scope of installation (namespaced or cluster)
cluster

- Others

/kind bug

### PR DESCRIPTION
**Pull request by font**
**What this PR does / why we need it**:
`kind` v0.4.0 now supports kube v1.15.0 so this updates the CI script to deploy and test against kube v1.15.0.

**Which issue(s) this PR fixes**:
Fixes #1079 

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by marun** [comment]
CI failure of CRD test looks legit - I'm guessing CRD support has changed between 1.14 and 1.15?

**Comment by font** [comment]
The CI failure was due to a couple of race conditions in the FTC controller e2e test after the v2 CRD update is performed:
1. Querying for all APIs and seeing `types.kubefed.io/v1` available, then a subsequent attempt to retrieve resources for this `GroupVersion` fails because the v1 API eventually goes away after the CRD is updated to v2.
2. If the case 1 above was not hit, then the attempt to retrieve the CRD resources under the `types.kubefed.io/v2` (after the CRD version is updated) would fail with no resources found.

This fix waits until the v2 target CRD is available within the `types.kubefed.io/v2` API (similar to the waiting for v1) before proceeding.

The only other failures I have seen were due to either #1084 or #1085, both of which existed before this k8s v1.15.0 PR. #1084 seems to be happening more often now.

**Comment by xunpan** [comment]
LGTM
Thanks for detailed explanation.

**Comment by abhat** [comment]
👍

**Pull request merged**
