### PR TITLE
Update to kubebuilder 0.2.0 and kube 1.14 

### PR DESCRIPTION
**Pull request by marun**
Kubernetes 1.16 requires structural schema for CRDs and generating compatible schema with kubebuilder requires updating to the latest version (0.2.0). This ensures that that the validation schema of types defined in code will include top-level `type: object`. 

This change also required updating the vendored versions of kube dependencies to 1.14 (the version used by kubebuilder 0.2.0).  Updating to a more recent version of kube depends on kubebuilder updating to that newer version first.

Partial fix for #1141

### CODE REVIEW

**Comment by xunpan** [comment]
LGTM

**Comment by jimmidyson** [comment]
Thanks @marun for this! How can we get this merged? We're looking to use kubefed as a library and upgrading controller-runtime (for the dynamic client) is essential for us to use it.

**Comment by marun** [comment]
@jimmidyson Just need a reviewer to do the honors, nothing blocking it. btw an update to 1.16 will likely follow as soon as [controller-runtime gets updated](https://github.com/kubernetes-sigs/controller-runtime/pull/588).

**Comment by xunpan** [comment]
As there is no other reviewers has concern about this, just merge it. 
/lgtm

**Pull request merged**
