### PR TITLE
chore: Disable SchedulerPreferences by default

### LINKED ISSUE #1329: Disable SchedulerPreferences feature by default
**What would you like to be added**:
`SchedulerPreferences` is marked as an alpha feature and enabled by default. We need to disable it by default due to its alpha nature.

**Why is this needed**:
 In order to mark kubefed as beta, we have to disable this feature by default.

/kind feature

### PR DESCRIPTION
**Pull request by swiftslee**
Signed-off-by: yuswift <yuswift2018@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1329 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by yuswift** [comment]
/cc @hectorj2f 
please take a look at this pr when you are free. Thanks.

**Comment by yuswift** [comment]
https://github.com/kubernetes-sigs/kubefed/runs/3057434203?check_suite_focus=true
The test failure seems to have nothing to do with this pr. Please retest.

**Comment by irfanurrehman** [comment]
@swiftslee can you please ensure that the EasyCLA requirement is satisfied for this one.
/remove-lifecycle-stale

**Comment by swiftslee** [comment]
> @swiftslee can you please ensure that the EasyCLA requirement is satisfied for this one. /remove-lifecycle-stale

I closed and reopened this pr, then the EasyCLA requirement is satisfied.
BTW, could you invite me to kubernetes-sig org? I think it will be more convenient to trigger the test such as `retest`.

**Pull request closed without merging**
