### PR TITLE
use kubectl apply to ensure that crds upgrade or handle re-install

### PR DESCRIPTION
**Pull request by s12chung**
**What this PR does / why we need it**:

Add `kubectl apply` via a Job in the helm chart to apply updates to CRDs and handles re-installing the chart because deleting a chart does not delete the CRDs

See https://joejulian.name/post/helm-v2-crd-management/

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by s12chung** [comment]
looks like CI failed, please me know your thoughts about the resulting chart changes because i dig into how the code is generated.

**Comment by hectorj2f** [comment]
@s12chung Please, explain why this PR is needed or open an issue explaining what this PR tries to fix. Rebase against master to see why this PR is failing.

**Comment by hectorj2f** [comment]
@s12chung could you address the comments here and rebase against master branch ?

**Pull request closed without merging**
